# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7dc8ca955db1258179e3e9cd2e42b7b26666c3e33dfc820f708cddd61bb7a9664919ad884ba4c0d1a31e72cd19768e4c7dbfd938584ec85e5e7b0bed38da8561

test:
  secret_key_base: a0095b4b6fc9cff06164978caa7cb21d704e6ba093a502ff0cdf9c6709ede92ce5e11666e0cb55a7fee7dcb6b66ff68990a36fd870805d8af0b346a2f2c138e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
